### ISSUE TITLE
pod install failed !!!

### ISSUE THREAD

**Issue by zhaozhongke** [DataEye/DataEyeAppAnalysis#2]
Installing DataEyeAppAnalysis (2.5.2)

[!] Error installing DataEyeAppAnalysis
[!] /usr/bin/git clone https://github.com/DataEye/DataEyeAppAnalysis.git /var/folders/98/9fxsk6_n09d13s24r9rw5glc0000gn/T/d20160526-40031-75i8p0 --single-branch --depth 1 --branch 2.5.2

Cloning into '/var/folders/98/9fxsk6_n09d13s24r9rw5glc0000gn/T/d20160526-40031-75i8p0'...
warning: Could not find remote branch 2.5.2 to clone.
fatal: Remote branch 2.5.2 not found in upstream origin

**Comment by wxq491216** [comment]
Thank you, it is my fault. Now, the tag 2.5.2 is ok.
